services:
  db:
    image: postgres
    container_name: postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes: 
      - blogs-app:/var/lib/postgresql/data

volumes:
  blogs-app: