POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Title",
    "author": "James",
    "url": "localhost.com",
    "likes": 123
}

### 

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "jtrau",
  "name": "james",
  "password": "123"
}

###
GET http://localhost:3003/api/blogs