POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp0cmF1IiwiaWQiOiI2N2E1MGNiNDE0ODJkMzhiYWE4OTg0MmEiLCJpYXQiOjE3Mzg4Njk5OTZ9.B2jM14oYy-LzyNIOe50Q1zxcMQ4A0D1EChQlczv7BSo

{
    "title": "Title",
    "author": "James",
    "url": "localhost.com",
    "likes": 123,
    "userId": "67a50cb41482d38baa89842a"
}

### 

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "jtrau",
  "name": "james",
  "password": "123"
}

###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "jtrau",
  "password": "123"
}
### 

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "grr",
  "password": "martin"
}

###
POST http://localhost:3003/api/users 
Content-Type: application/json

{
  "username": "grr",
  "password": "martin",
  "name": "George R. R. Martin"
}

###

POST http://localhost:3003/api/testing

### 

GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs/67ce2291171765cfefb928ad/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp0cmF1IiwiaWQiOiI2N2NlMjI5MDE3MTc2NWNmZWZiOTI4YTIiLCJpYXQiOjE3NDQ0MDIyMTF9.TKbc-3hqun3PniN93tXUWyWrxaI9s-_Ga7KQ2vjP1I8

{
  "comment": "test comment"
}